<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>PrinterCollector.Tools.PeCallsites</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Iced" Version="1.21.0" />
  </ItemGroup>
</Project>
